Issue_Tracker/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("Tracker.urls")),
    path('captcha/', include('captcha.urls')),
]



urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

Tracker/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('signup/', signUp, name='signup'),
    path('login/', loginView, name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('',home, name='home'),
    path('addproduct/',addProduct, name='addproduct'),
    path('addissue/',addIssue, name='addissue'),
    path('issues/<str:id>',getIssue, name='issue'),
    path('issues/', getAllIssues, name='issues'),
    path('privateissues/',viewPrivateIssues, name='privateissues'),
    path('adminprivateissues/',viewAdminPrivateIssues, name='adminprivateissues'),
    # path('privateissues/<str:id>',getIssue, name='privateissues'),
    # path('adminprivateissues/<str:id>',getIssue, name='adminprivateissues'),
    # path('addcomment/',addComment, name='addcomment'),
    # path('addfeedback/',addFeedback, name='addfeedback'),
    path('ajax/load-products/',load_products, name='load_products'),
    path('changepassword/', change_password, name='changepassword'),
    path('user/<str:id>',getUser,name='getuser'),
    path('profile/<str:id>',getProfile,name='getprofile'),
    path('editprofile/', editProfile, name='editprofile'),
    path('editissue/<uuid:issue_id>/', editIssue, name='editissue'),
    path('editfeedback/<uuid:feedback_id>/', editFeedback, name='editfeedback'),
    path('companydetails/<uuid:company_id>/', companyDetails, name='companydetails'),
    path('issue/<uuid:issue_id>/changestatus/', changeIssueStatus, name='changeissuestatus'),
    path('support/', supportForm, name='support'),
    path('hiring/',hiringForm, name='hiring'),
    path('supportlist/',supportList, name='supportlist'),
    path('hirings/',hiringList, name='hirings'),
    path('reportissue<str:id>/',reportIssue, name='reportissue'),
    path('reportfeedback<str:id>/',reportFeedback, name='reportfeedback'),
    path('reportcomment<str:id>/',reportComment, name='reportcomment'),
    path('reporthiringcomment<str:id>/',reportHiringComment, name='reporthiringcomment'),
    path('productstats/<str:product_id>/', productStatsView, name='productstats'),

    # path('hirings/<str:id>',getHiring, name='hirng'),
    path('supportformsuccess/', supportFormSuccess, name='supportformsuccess'),
    path('issue/<str:issue_id>/addcomment/', add_comment, name='addcomment'),
    path('getlogs/<str:id>',getLogs, name='getlogs'),
    path('getissuestatuslogs/<str:id>',getIssueLogs, name='getissuestatuslogs'),
    path('hiringissue/<str:hiring_id>/addcomment/', add_hiring_comment, name='addhiringcomment'),
    path('issue/<str:issue_id>/addfeedback/', add_feedback, name='addfeedback')
]

Tracker/models.py
from django.db import models
import json
from django.contrib.auth.models import AbstractUser
import uuid
from django.contrib.postgres.fields import ArrayField
# Company model
class Company(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    url = models.URLField(max_length=255)
    email = models.EmailField(max_length=255)
    bio = models.TextField()
    pic = models.ImageField(upload_to='company_pics/', null=True, blank=True)
    def __str__(self):
        return self.name

# User model
class User(AbstractUser):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    username = models.CharField(max_length=255, unique=True)
    image=models.ImageField(upload_to='images',default="/images/Empty-image.jpg")
    password = models.CharField(max_length=255)
    firstname = models.CharField(max_length=255)
    lastname = models.CharField(max_length=255)
    email = models.EmailField(max_length=255, unique=True)
    companyuser=models.BooleanField(default=False)
    enabled=models.BooleanField(default=True)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='users',null=True, blank=True)

    def __str__(self):
        return self.username
    @property
    def custom_username(self):
        if self.is_staff:  # Assuming admin users are flagged with is_staff
            return f"{self.username} (Admin)"
        elif self.companyuser:
            return f"{self.username} ({self.company.name})"
        else:
            return self.username

# Product model
class Product(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=255)
    url = models.URLField(max_length=255)
    company = models.ForeignKey(Company, on_delete=models.CASCADE, related_name='products')

    def __str__(self):
        return self.name
class Tag(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(max_length=255,blank=True,null=True)
    user = models.ForeignKey(User, null=True,on_delete=models.CASCADE)

    def __str__(self):
        return self.name
# Issue model
class Issue(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    STATUS_CHOICES = [
        ('created', 'Created'),
         ('viewed', 'Viewed'),
        ('investigating', 'Investigating'),
        ('fixed', 'Fixed'),
        ('cannotfix','CannotFix')
    ]

    issuename = models.CharField(max_length=255)
    enabled=models.BooleanField(default=True)
    description = models.TextField()
    created_by = models.ForeignKey('User', on_delete=models.CASCADE,)
    company = models.ForeignKey('Company', on_delete=models.CASCADE,)
    product = models.ForeignKey('Product', on_delete=models.CASCADE, null=True, blank=True)
    tags = models.ManyToManyField('Tag')
    status = models.CharField(max_length=50, choices=STATUS_CHOICES,default='created')
    viewcount = models.PositiveIntegerField(default=0)
    feedbackcount = models.PositiveIntegerField(default=0)
    commentcount = models.PositiveIntegerField(default=0)
    private=models.BooleanField(default=False)
    pinned=models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.issuename


# Comment model
class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE, related_name='comments')
    enabled=models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='comments')
    description = models.TextField()
    pinned=models.BooleanField(default=False)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.issue.issuename}'



# Feedback model
class Feedback(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    CHOICES = [
        ('option1', 'option1'),
        ('option2', 'option2'),
        ('option3', 'option3'),
    ]
    options = models.CharField(max_length=100,choices=CHOICES)
    bool=models.BooleanField(default=False)
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE, related_name='feedbacks')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='feedbacks')
    enabled=models.BooleanField(default=True)
    comment = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    pinned=models.BooleanField(default=False)

    def __str__(self):
        return f'Feedback by {self.user.username} on {self.issue.issuename}'

# ViewedBy model
class ViewedBy(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='vieweduser')
    timestamp = models.DateTimeField(auto_now_add=True)
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE, related_name='viewedissue')

    def __str__(self):
        return f'{self.user.username} viewed {self.issue.issuename}'


class Support(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    QUERY_TYPES = [
        ('query', 'Query'),
        ('feedback', 'Feedback'),
        ('technical_issue', 'Technical Issue'),
    ]

    type = models.CharField(max_length=20, choices=QUERY_TYPES)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.get_type_display()} - {self.created_at}"

class Hiring(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    CHOICES = [
        ('option1', 'option1'),
        ('option2', 'option2'),
        ('option3', 'option3'),
    ]
    name = models.CharField(max_length=100)
    url = models.URLField()
    options = models.CharField(max_length=100,choices=CHOICES)
    description = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    pinned = models.BooleanField(default=False)
    timestamp= models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.name} - {self.created_at}"
    
class HiringComment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    hiring = models.ForeignKey(Hiring, on_delete=models.CASCADE,)
    enabled=models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE,)
    description = models.TextField()
    pinned=models.BooleanField(default=False)

    def __str__(self):
        return f'Comment by {self.user.username} on {self.hiring.name}'
    
class FeedbackLogs(models.Model):
    feedback = models.ForeignKey(Feedback, on_delete=models.CASCADE)
    old_values = models.TextField(null=True,blank=True)
    new_values = models.TextField(null=True,blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    log_entry = models.TextField(null=True,blank=True)

class IssueStatusLog(models.Model):
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE)
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    oldstatus=models.TextField(null=True,blank=True)
    newstatus=models.TextField(null=True,blank=True)
    log_entry = models.TextField(null=True,blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)

class ReportIssue(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    issue = models.ForeignKey(Issue, on_delete=models.CASCADE)
    description=models.TextField(null=True,blank=True)
    CHOICES = [
        ('option1', 'option1'),
        ('option2', 'option2'),
        ('option3', 'option3'),
    ]
    options = models.CharField(max_length=100,choices=CHOICES)

class ReportComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    description=models.TextField(null=True,blank=True)
    CHOICES = [
        ('option1', 'option1'),
        ('option2', 'option2'),
        ('option3', 'option3'),
    ]
    options = models.CharField(max_length=100,choices=CHOICES)

class ReportHiringComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.ForeignKey(HiringComment, on_delete=models.CASCADE)
    description=models.TextField(null=True,blank=True)
    CHOICES = [
        ('option1', 'option1'),
        ('option2', 'option2'),
        ('option3', 'option3'),
    ]
    options = models.CharField(max_length=100,choices=CHOICES)

class ReportFeedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    feedback = models.ForeignKey(Feedback, on_delete=models.CASCADE)
    description=models.TextField(null=True,blank=True)
    CHOICES = [
        ('option1', 'option1'),
        ('option2', 'option2'),
        ('option3', 'option3'),
    ]
    options = models.CharField(max_length=100,choices=CHOICES)
    

Tracker/templates/Issue.html
{% extends "base.html" %}
{% load static %}

{% block title %}Add Issue{% endblock %}

{% block content %}
<div class="create-issue-main">
<div id="terms" class="terms">
    <h2>Terms and Conditions</h2>
    <ul>
        <li>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et lectus
            neque. Proin nec commodo arcu. Nullam fringilla lacinia diam, vel
            ultrices mauris consectetur at. Quisque sit amet ligula eget felis
            vestibulum pharetra. Donec vel fringilla ligula. Sed ut placerat sapien.
            Nam volutpat lacus eu velit dignissim, ut consectetur leo efficitur. Sed
            eu dapibus lorem. Phasellus sit amet elit sed magna dictum volutpat.
        </li>
        <li>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et lectus
            neque. Proin nec commodo arcu. Nullam fringilla lacinia diam, vel
            ultrices mauris consectetur at. Quisque sit amet ligula eget felis
            vestibulum pharetra. Donec vel fringilla ligula. Sed ut placerat sapien.
            Nam volutpat lacus eu velit dignissim, ut consectetur leo efficitur. Sed
            eu dapibus lorem. Phasellus sit amet elit sed magna dictum volutpat.
        </li>
        <li>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed et lectus
            neque. Proin nec commodo arcu. Nullam fringilla lacinia diam, vel
            ultrices mauris consectetur at. Quisque sit amet ligula eget felis
            vestibulum pharetra. Donec vel fringilla ligula. Sed ut placerat sapien.
            Nam volutpat lacus eu velit dignissim, ut consectetur leo efficitur. Sed
            eu dapibus lorem. Phasellus sit amet elit sed magna dictum volutpat.
        </li>
    </ul>
    <button id="acceptTerms">Accept Terms</button>
</div>

<!-- Issue Form (Initially Hidden) -->
<div id="issueForm" style="display: none">
    <div class="issue-form-container">
        <form id="addIssueForm" class="form" method="post" enctype="multipart/form-data">
            <h2>Create Issue</h2>
            {% csrf_token %}
            {{ form.as_p |safe }}
            <button type="submit">Submit</button>
        </form>
        <!-- Display form errors -->
        {% if form.errors %}
            <div class="form-errors">
                <ul>
                    {% for field in form %}
                        {% for error in field.errors %}
                            <li>{{ error }}</li>
                        {% endfor %}
                    {% endfor %}
                    {% for error in form.non_field_errors %}
                        <li>{{ error }}</li>
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
    </div>
</div>

<!-- Loader (Initially Hidden) -->
<div id="loader" style="display: none;">
    <img src="{% static 'path/to/loader.gif' %}" alt="Loading...">
</div>
</div>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/tagify/4.9.1/tagify.min.js"></script>
<script>
    var taglist = {{ taglist|safe }}
    var input = document.querySelector('input[name=tags_field]');
    // initialize Tagify on the above input node reference
    new Tagify(input, {
        whitelist: taglist,
        dropdown: {
            mapValueTo: 'full',
            classname: 'tagify__dropdown--rtl-example',
            enabled: 0, // shows the suggestiosn dropdown once field is focused
            RTL: true,
            escapeHTML: false // allows HTML inside each suggestion item
        }
    })
</script>    

<script type="text/javascript">
    $(document).ready(function () {


        $("#id_company").change(function () {
            var url = "{% url 'load_products' %}";
            var companyId = $(this).val();

            $.ajax({
                url: url,
                data: {
                    company_id: companyId,
                },
                success: function (data) {
                    $("#id_product").html("");
                    $("#id_product").append('<option value="">---------</option>');
                    if (data.length > 0) {
                        $.each(data, function (key, value) {
                            $("#id_product").append(
                                '<option value="' +
                                value.id +
                                '">' +
                                value.name +
                                "</option>"
                            );
                        });
                    }
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.log('Error loading products:', textStatus, errorThrown);
                }
            });
        });

        function toggleIssueForm(visible) {
            if (visible) {
                $("#issueForm").show();
            } else {
                $("#issueForm").hide();
            }
        }

        toggleIssueForm(false);

        $("#acceptTerms").click(function () {
            toggleIssueForm(true);
            $("#terms").hide();
        });

        $("#addIssueForm").submit(function (event) {
            event.preventDefault(); 

            // Show loader
            $("#loader").show();

            // Log form data before AJAX submission
            console.log("Form data:", $(this).serialize());
            var form = $(this)[0]; 
            var formData = new FormData(form);

            // Ensure that the product field data is included in FormData
            // Assuming id_product is the ID of the select input for product
            formData.append('product', $('#id_product').val());

            $.ajax({
                url: $(this).attr("action"),
                type: $(this).attr("method"),
                data: formData,
                processData: false,
                contentType: false,
                success: function (data) {
                    console.log("Form submitted successfully");
                    // Optionally redirect after successful submission
                    window.location.href = "{% url 'issues' %}";
                },
                error: function (jqXHR, textStatus, errorThrown) {
                    console.error("Form submission error:", errorThrown);
                    alert("Error submitting form. Please try again.");
                },
                complete: function () {
                    // Hide loader
                    $("#loader").hide();
                }
            });
        });
    });
    

    document.querySelector('.company').addEventListener('change', function() {
    if(!this.value){
        const elements = document.querySelectorAll('.company-data');
        elements.forEach(element => {
            const parent = element.parentElement;
            if (parent) {
                parent.style.display = 'block';
            }
        });
    }
    if (this.value && this.value!='') {
        const elements = document.querySelectorAll('.company-data');
        elements.forEach(element => {
            const parent = element.parentElement;
            if (parent) {
                parent.style.display = 'none';
            }
        });
    }
});

document.querySelector('.product').addEventListener('change', function() {
    if(!this.value){
        const elements = document.querySelectorAll('.product-data');
        elements.forEach(element => {
            const parent = element.parentElement;
            if (parent) {
                parent.style.display = 'block';
            }
        });
    }
    if (this.value && this.value!='') {
        const elements = document.querySelectorAll('.product-data');
        elements.forEach(element => {
            const parent = element.parentElement;
            if (parent) {
                parent.style.display = 'none';
            }
        });
    }
});
</script>
{% endblock %}

Tracker/templates/addhiringcomment.html
{% extends "base.html" %}
{% load static %}
{% block title %}Add Comment{% endblock %}
{% block content %}
<div class="form-container">
    <form method="post" class="form hiring-form">
        <h1>Add Comment</h1>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit Comment</button>
    </form>
</div>
{% endblock %}

Tracker/templates/base.html
<!DOCTYPE html>
<html>
	<head>
		<title>{% block title %}Issue Tracker{% endblock %}</title>
		{% load static %}
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, intitial-scale=1" />
		<link
			rel="stylesheet"
			href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" />
		<link rel="preconnect" href="https://fonts.googleapis.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
		<link
			href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
			rel="stylesheet" />
		<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"></script>
		<link
			href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
			rel="stylesheet" />
		<!-- Add these lines to your base template or the template where you have the form -->
		<link
			rel="stylesheet"
			href="https://cdn.jsdelivr.net/npm/@yaireo/tagify/dist/tagify.css" />
		<script src="https://cdn.jsdelivr.net/npm/@yaireo/tagify"></script>
		<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
		<link
			href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
			rel="stylesheet" />
		<link
			rel="stylesheet"
			href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" />
		<link rel="stylesheet" href="{% static 'styles.css' %}" />
	</head>
	<body>
		{% include 'header.html' %}
		<main>{% block content %}{% endblock %}</main>
		<script>
			document.addEventListener("DOMContentLoaded", function () {
				var labels = document.querySelectorAll("form label");

				labels.forEach(function(label) {
					var labelText = label.innerHTML; 
					label.innerHTML = labelText.replace(':', '');
				});
			});
		</script>

	</body>
</html>

Tracker/templates/companydetails.html
{% extends "base.html" %}
{% load static %}
{% block title %}Company Details{% endblock %}
{% block content %}
    <div class="company-container">
        <div class="grid-container">
            <div class="company-info full-width">
                <h2>{{ company.name }}</h2>
                <p><strong>URL:</strong> <a href="{{ company.url }}">{{ company.url }}</a></p>
                <p><strong>Email:</strong> {{ company.email }}</p>
                <p><strong>Bio:</strong> {{ company.bio }}</p>
            </div>
            <div class="users">
                <h2>Users</h2>
                <ul>
                    {% for user in users %}
                    <li>{{ user.firstname }} {{ user.lastname }} ({{ user.custom_username }})</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="issues">
                <h2>Satistics for all Issues</h2>
                <p><strong>Total Issues Created:</strong> {{ issues_count }}</p>
                <h3>Total issues grouped by status</h3>
                <ul>
                    {% for status_choice, status_name in status_choices.items %}
                        <li>{{ status_name }}: 
                            {% for status_count in status_counts %}
                                {% if status_count.status == status_choice %}
                                    {{ status_count.count }}
                                {% endif %}
                            {% endfor %}
                        </li>
                    {% endfor %}
                </ul>

                <!-- Display tag counts -->
                <h3>Total Issues Grouped by Tags:</h3>
                <ul>
                    {% for tag,count in tag_counts.items %}
                        <li>{{ tag}}: {{ count}}</li>
                    {% endfor %}
                </ul>
                
                <h3>Issue Names</h3>
                <ul>
                    {% for issue in issues %}
                    <li>{{ issue.issuename }}</li>
                    {% endfor %}
                </ul>
            </div>
            <div class="products">
                
                <ul>
                    {% for product in products %}
                    <li>
                        <h2>Statistics for all issues for {{ product.name }} </h2>
                        <strong>Product Name:</strong> {{ product.name }}<br>
                        <strong>Product URL:</strong> <a href="{{ product.url }}">{{ product.url }}</a><br>
                        <strong>Total Issues:</strong> 
                        {% for product_stat in product_stats %}
                            {% if product_stat.product.id == product.id %}
                                {{ product_stat.total_issues }}
                            {% endif %}
                        {% endfor %}
                        <br>
                        <h2><strong>Total Issues Grouped By Status:</strong></h2>
                        <ul>
                            {% for product_stat in product_stats %}
                                {% if product_stat.product.id == product.id %}
                                    {% for status, count in product_stat.status_counts.items %}
                                        <li>{{ status }}: {{ count }}</li>
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                        </ul>
                        <h2><strong>Total Issues Grouped By Tags:</strong></h2>
                        <ul>
                            {% for product_stat in product_stats %}
                                {% if product_stat.product.id == product.id %}
                                    {% for tag, count in product_stat.tag_counts.items %}
                                        <li>{{ tag }}: {{ count }}</li>
                                    {% endfor %}
                                {% endif %}
                            {% endfor %}
                        </ul>
                    </li>
                    {% endfor %}
                </ul>
            </div>
           
        </div>
    </div>
{% endblock %}

Tracker/templates/edituserprofile.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    User Profile
{% endblock %}


{% block content %}
<div class="profile-container">
    <div class="profile-header">
        <div class="profile-image">
            <img src="{{ user.image.url }}" alt="{{ user.custom_username }}">
        </div>
        <div class="profile-info">
			<a href="{% url 'editprofile' %}" class="btn btn-primary">Edit Profile</a>
            <h1>{{ user.custom_username }}</h1>
            <h4>First Name : {{ user.firstname }}</h4>
            <h4>Last Name : {{ user.lastname }}</h4>
            <p class="bio">{{ user.bio }}</p>
            <div class="profile-stats">
                <div class="stat">
                    <strong>{{ issues_count }}</strong>
                    <span><i class="fas fa-bug"></i> Issues Created</span>
                </div>
                <div class="stat">
                    
                    <strong>{{ feedbacks_given }}</strong>
                    <span><i class="fas fa-lightbulb"></i> Feedbacks Given</span>
                </div>
                <div class="stat">
                   
                    <strong>{{ comments_created }}</strong>
                    <span> <i class="fas fa-comments"></i> Comments Created</span>
                </div>
            </div>
        </div>
		 
    </div>

    <div class="tags-section">
        <h2>List of Tags Created</h2>
        <div class="tags">
            {% for tag in tags %}
                <span class="tag">{{ tag.name }}</span>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

Tracker/templates/feedbacklogs.html
{% extends "base.html" %}

{% block content %}
  <div class="issue-status-logs">
    <h2 class="title">Feedback Logs</h2>
    <div class="log-list">
      {% for log in logs %}
        <div class="log-card">
          <div class="log-card-header">
            <h5 class="log-card-title">User: {{ log.feedback.user.username }}</h5>
          </div>
          <div class="log-card-body">
            <p class="log-card-text">
              <strong>Timestamp:</strong> {{ log.timestamp }}<br>
            </p>
            <p class="log-card-entry">{{ log.log_entry }}</p>
          </div>
        </div>
      {% endfor %}
    </div>
  </div>
{% endblock %}

Tracker/templates/hiringform.html
{% extends "base.html" %}
{% load static %}
{% block title %}Hiring{% endblock %}
{% block content %}
<div class="contact-main">
    <img src="{% static 'img/hiring.jpg' %}"/>
<div class="issue-form-container">
<form method="post" class="form">
    <h2>Hiring</h2>
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Submit</button>
</form>
</div>
</div>
{% endblock %}